### ISSUE TITLE
Create a Vagrantfile

### ISSUE THREAD

**Issue by ericderegt** [NYU-DevOps-Spring2018-Orders/orders#1]
**As a** Developer  
**I need** a Vagrantfile  
**So that** members of the team can use the same development environment  

**Assumptions:**
* We will use the base Vagrantfile from class but remove the Redis part
* Add requirements text file to ensure packages are installed at the version needed

**Acceptance Criteria:**
```
When I run vagrant up && vagrant ssh I should be able to start developing.
```

**Comment by andyd0** [comment]
Added requirements.txt to this
