### ISSUE TITLE
Cancel an order - Action REST function

### ISSUE THREAD

**Issue by t3ychenzhan** [NYU-DevOps-Spring2018-Orders/orders#10]
**As a User
**I need access orders
**So that I can perform some Action on the orders

**Assumptions:**
* .../orders/int:id is the route

**Acceptance Criteria:**
```
Given orders/id,
When search
Then I can perform some other actions on orders.

Rest function should also be set up with a test case to ensure function is working properly
```

**Comment by ericderegt** [comment]
When we meet again this week we should try and narrow down what this action should be

**Comment by andyd0** [comment]
Might require asking the professor - in the assignment it mentions "action on the resource" but not clear what that would be
