### ISSUE TITLE
Discussion of a scope of orders

### ISSUE THREAD

**Issue by hjcho7311** [NYU-DevOps-Spring2018-Orders/orders#3]
**As a** ...  developer
**I need** ...  to figure out a scope of orders
**So that** ...  team understand the scope of our service

**Assumptions:**
* We need to decide order attribute, etc.

**Acceptance Criteria:**
```
When the team has decided what to include in the order
Then create and update models.py
```

**Comment by hjcho7311** [comment]
I did not know I cannot delete the issue after submit new issue.
I will edit this issue#3 and reopen it.

**Comment by ericderegt** [comment]
So far we have discussed the following properties for the model

Order id
Customer id
Product id
Product qty
Price
Order status

**Comment by andyd0** [comment]
Yeah, those make sense to me.  Maybe we need to also keep track of what promotion is used (and any other team data)?  Will require knowing what are the other schemas.  I also wonder if in the end all the projects will work together to provide the end result website.

**Comment by yaraqian** [comment]
In addition, is there only one kind of product in the orders?
