### ISSUE TITLE
Get a list of orders - List REST Function

### ISSUE THREAD

**Issue by ericderegt** [NYU-DevOps-Spring2018-Orders/orders#8]
**As a** User  
**I need** to access a list endpoint  
**So that** I can consume all of the orders  

**Assumptions:**
* /orders is the endpoint
* GET method

**Acceptance Criteria:**
```
When I run the server locally, if go to /orders, I should get a list of all of the orders

Rest function should also be set up with a test case to ensure function is working properly
```

**Comment by andyd0** [comment]
Should we mention anything about testing?

**Comment by andyd0** [comment]
Also, should we treat these as enhancements?  I guess we can check is demo board

**Comment by andyd0** [comment]
Adding this to all Rest functions...

"Rest function should also be set up with a test case to ensure function is working properly"
